# Generated by Django 5.2 on 2025-04-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_appointment_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
